From: a@example.com
To: b@example.com
Subject: s
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=example.com; s=sel; t=1700000000; h=from:to:subject; bh=frcCV1k9oG9oKj3dpUqdJg1PxRT2RSN/XKdLCPjaYaY=; b=KxKJYnynEvXTlXBKiQLXft0uE/P1tfN8Ee53V2edmG7Wn+RbTogsTnpGmnkmBGngWwu2rF05YosyDHBIQAWj5+TB1VOAz21GF8p3FMTXU8eXHcoyimAgd3YTy66qoE/7DkY2Ou0ffXAMmq5P+r8Q2uFb+W+eISay1pjmRLFkdbZLZHLo+QzMAJmGxPHXFp6sQ/OaRg4G3LdB/n/fnnEHP7gNpSQh+zmUQOZVHxgmvqVFF6O4yHDFCv9wOpZQl68iIPPDb7QQoekgcIM9dufO5WAhQpLWDMMFfai5g1/Y/hkCEVLIgpJvG7go8DFn3kFPQXBxKLJDRXC2vpL5BUa3iw==

