From: a@example.com
To: b@example.com
Subject: s
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=example.com; s=sel; t=1700000000; h=from:to:subject; bh=G/7sqsM5RiV5f4ZhWl5FMS2dTa6FvR04pSlABPPAaRo=; l=25; b=XruqA/tA/yndzs+ovk+77CXNYWeDkblyHa/VR1+t876SZ7FecitYpnD9BYe8rHBnUCwZLSXsN7j1BEX6nwldaRHXpdwhb/RFuTIKM+K9tdq+FxfmcO2MeSSQhdsZ9sP3oWs6fqVi3rEjgXppTRl9l2pz8nwX6bXmhdc6HjOb08Dex3esPHn76hYexmbEM6/rFCuhq0ppp1HH83bHAef9aB7u6YA+t+mXTQK3zRDI9oH4r44/7UNBoPekNXBffDNFLpBxyX8dsG7MPDcHOJMMFFq5U8lqEO1fOJ6TyYWscSjzJqkod0rboE+E1adFb2YKTFxr6toMpm/Hbnnj6lKtPA==

0123456789abcdef
