From: a@example.com
To: b@example.com
Subject: s
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=example.com; s=sel; t=1700000000; h=from:to:subject; bh=GVz/CG5ZsAtKynLk6yzbqFfB4F5h3X5ZmXt9rc6jZRI=; b=Mx66pohnCrEXukRcNoiPYeTjcrnl9ANRRjHsYuq6u3uU5KAJH+YpkmpcG1KCMCpGmDEhDKywyK5o+KLJPZaURMCdoVfsFWPAn3rvgDJ81ThVcztYG0IHWMdhmw98czaQ4Eh5loyB4Ab8gtXuHg6k37P5K/j8nxpv9TkzRhu17bwobz2+Ixsbqy86/hyejVW8daNY08LDcCCx8wOUk4z8vhxvVdZi/auOT6GFxnvZ1RwKBwnrmKHMZnyy+mKu8IgJXXVF5Mqcg3dRM2lVuoPhaZURDraM6YzrmtuydoGm/tbPM7C9BfcftsBqlNDZoy/t5sIunH7xJ1bTjAmOdDQu/Q==

body line
