Received: from one.example by mx.example; Fri, 1 Jan 2027 00:00:00 +0000
Received: from two.example by mx.example; Fri, 1 Jan 2027 00:00:01 +0000
From: a@example.com
To: b@example.com
Subject: s
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=example.com; s=sel; t=1700000000; h=received : received : from : to : subject; bh=GVz/CG5ZsAtKynLk6yzbqFfB4F5h3X5ZmXt9rc6jZRI=; b=awBiwmx6181sPrK0xIwFAlgKbZ0DrDQOad4p/8hmb9HTAt4mIg8O+uaR6uo5N+MGkmYm7IDaqwRCg/BkL5IPajVjgtbfNLjCeQm3sdh7wg8CzFdIzNWGkawvcRBEaDpKbGT4vNy19uS3B8KHIE3hvgyEKWbfC+PHOFf2K/7D/TSxLCo0KUJV9NftxoyPM86BnV7pQN1XopsJ/aujK1xN6wF8tTEaVt8Nvrdo7K3XdBoosCuchh9bIHoJ99KciNG2Uwzw3zkFEfMpgUIS6EprHBkECiZDa5mByxssQBGz8yZSCGa927RJhod1Mk5lTOgnZdrG3c870EZS/liK5fd2WA==

body line
