From: a@example.com
To: b@example.com
Subject: s
dkim-signature: v=1; a=rsa-sha256; c=simple/simple; d=example.com; s=sel; t=1700000000; h=from:to:subject; bh=GVz/CG5ZsAtKynLk6yzbqFfB4F5h3X5ZmXt9rc6jZRI=; b=B8Z0sgMueMc9DjW1ywSHg5mBBm/TmNSscwhrXM6JbaZwpjsOr4EEqR4xcLpzxOeIRHrAS96Uys5QAICTas6twYlMyJNmKqt6jqKBO6a1LDsNVX/8QHS6ET9dXqPVe6oARj8r8+8uGavqOssfIyF9PCt+4L9YtJB9A/Bl1D/iZ5OIquB8etRuQKUOhvvSRs/hCVf//UP2Wp4rZ6XpsTlW+IxoMQEj7So1ccULTXPvLYRQmKaoJ0bpmAKTGUsYgCaH1FCWdZAEfTSGYmaaURiyReqaIXXl2FEr54+VN21soy//GiGzfw0fcIdn08VBsknvWX/sr8PZyoFRB8SqCWhktA==

body line
