From: a@example.com
To: b@example.com
Subject: s
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=example.com; s=sel; t=1700000000; h=from:to:subject; bh=XshJ6KTcDkLYOYqK3COXhm+zdPEGKEwYqNtjLpo1nt0=; b=B4Jm6GUmChsN3RL4DRc1HYIXYV+IvbBtvCFB8Y1QBqvg17HeothO9F+X4Tc8JjAxpuurMBWumypH1mhbKHWaEv9CpfYOQ6AyMAdKdG7szeQxtxyIImd9/pX0cMgsvt/sfzqiWkaz9+97iiwDg5Fbp7AQnMO0aTcVv0sOYJvBb+OlEY9h0oZffNjJrM4fUd/88ecTYBas4681CAB9c2PH7VFS/bbSu4wfnyM4LxfY0+DXFSz3s0AC9AZdnP8xxnIbiPqrkGvKYSuOZXlamccpucoC6r0ZWNmhQvulxvZ8+SfQtyZTSt+9j40QM8tSwLDXqA2R+HQv8E+Bwk0QRvnRTw==

 Leading space body
second line
