/**
 * Session minting and validation.
 *
 * This is the template's `apps/api/services/auth/session.ts`, not `roley`'s
 * `managers/session.ts`: it avoids hashing a session token on every request and
 * keeps a negative cache for tokens already known to be dead. The source's
 * bcrypt-on-every-validation was a per-request CPU cost the template had already
 * dropped, so the port starts from the better descendant.
 *
 * What changed while porting it here:
 *
 *  - users and sessions come from an injected `SessionStore`, not a repository
 *    generated by a Prisma-shaped client, so the same manager runs over Postgres,
 *    SQLite or an in-memory fake;
 *  - the pepper arrives through `CryptoContext`, which throws if it is missing;
 *  - the negative cache is injected and expires through the fixed TTL cache, so a
 *    dead-token entry no longer inherits the `ttl * 1000` bug;
 *  - the extra half of the session token is returned exactly once, to the caller
 *    that sets the cookie, rather than being reconstructed from storage.
 *
 * The raw token is opaque and carries a format digest, so a well-formed-looking
 * cookie cannot be distinguished from a real one by length or shape.
 */

import type { CacheValue } from "./cache.ts"
import type { CryptoContext } from "./crypto.ts"
import type { ISessionManager, Session, SessionBase } from "./types.ts"
import { DEFAULT_SESSION_DURATION_MIN, DEFAULT_SESSION_LENGTH } from "./constants.ts"
import { getRandomString } from "./random.ts"

/** Persistence for sessions alone. A subset of `Adapter`, so an `Adapter` satisfies it. */
export interface SessionStore {
  getSession(id: number): Promise<null | Session>
  getAllSessions(userId: number): Promise<Session[]>
  createSession(
    session: Pick<SessionBase, "token" | "userId" | "keyId" | "expiresAt">,
  ): Promise<null | Session>
  updateSession(id: number, session: Partial<SessionBase>): Promise<null | Session>
  deleteSession(id: number): Promise<void>
  deleteAllSessions(userId: number): Promise<void>
  deleteExpiredSessions(): Promise<void>
}

/** TTL cache for tokens known to be dead. `get` returns `true` for a dead token. */
export interface NegativeSessionCache {
  get(key: string): Promise<undefined | CacheValue>
  set<T>(key: string, value: T, ttlMs: number): Promise<void>
}

/** Session-manager configuration. Every field has a documented default. */
export interface SessionManagerOptions {
  store: SessionStore
  crypto: CryptoContext
  /** Negative cache for dead tokens. Omitted disables the cache. */
  negativeCache?: NegativeSessionCache
  /** TTL of a negative-cache entry, in milliseconds. */
  negativeCacheTtlMs?: number
  /** Characters in a generated token. */
  sessionLength?: number
  /** Session lifetime in minutes. */
  sessionDurationMin?: number
  /** Clock, for tests. Defaults to `Date.now`. */
  now?: () => number
}

/** One day: a dead token stays dead for the lifetime of a valid one. */
const DEFAULT_NEGATIVE_CACHE_TTL_MS = 24 * 60 * 60 * 1000

/** Reject a token whose declared id is not a positive integer. */
const SESSION_ID_PATTERN = /^[1-9][0-9]*$/

/**
 * Mints, validates, refreshes and revokes sessions.
 *
 * The cookie value is `<sessionId>:<rawToken>` — the id lets validation fetch one
 * row instead of scanning, and the raw token never reaches storage, only its
 * pepper-bound PBKDF2 digest does.
 */
export class SessionManager implements ISessionManager {
  private readonly store: SessionStore
  private readonly crypto: CryptoContext
  private readonly negativeCache: NegativeSessionCache | undefined
  private readonly negativeCacheTtlMs: number
  private readonly sessionLength: number
  private readonly sessionDurationMin: number
  private readonly now: () => number
  private readonly sessionDurationMs: number

  constructor(options: SessionManagerOptions) {
    this.store = options.store
    this.crypto = options.crypto
    this.negativeCache = options.negativeCache
    this.negativeCacheTtlMs = options.negativeCacheTtlMs ?? DEFAULT_NEGATIVE_CACHE_TTL_MS
    this.sessionLength = options.sessionLength ?? DEFAULT_SESSION_LENGTH
    this.sessionDurationMin = options.sessionDurationMin ?? DEFAULT_SESSION_DURATION_MIN
    this.sessionDurationMs = this.sessionDurationMin * 60 * 1000
    this.now = options.now ?? Date.now
  }

  /**
   * Build the stored session and the matching raw token, without persisting.
   *
   * Split out because the signup flows build a session body *before* the user row
   * exists — they hand it to the adapter so user, key and session land in one
   * transaction.
   */
  async createBody(
    session: Pick<SessionBase, "userId" | "keyId">,
  ): Promise<{ notHashedToken: string; session: SessionBase }> {
    const notHashedToken = getRandomString(this.sessionLength)
    return {
      notHashedToken,
      session: {
        ...session,
        token: await this.crypto.hash(notHashedToken),
        expiresAt: this.getSessionExpirationDate(),
      },
    }
  }

  /** Mint a session. The returned session's `token` is the raw value, shown once. */
  async create(session: Pick<SessionBase, "userId" | "keyId">): Promise<null | Session> {
    const body = await this.createBody(session)
    const stored = await this.store.createSession(body.session)
    if (!stored) {
      return null
    }
    return { ...stored, token: body.notHashedToken }
  }

  /**
   * Validate a cookie value and, when the session is in its last quarter of life,
   * extend it. Returns the session with the raw token so the caller can re-issue a
   * cookie; returns `null` for every failure without saying which check failed.
   */
  async validate(sessionIdToken: string): Promise<null | Session> {
    if (this.negativeCache && await this.negativeCache.get(sessionIdToken)) {
      return null
    }
    const parsed = this.parseSessionIdToken(sessionIdToken)
    if (!parsed) {
      await this.rememberDead(sessionIdToken)
      return null
    }
    const session = await this.store.getSession(parsed.id)
    if (!session || !(await this.crypto.verify(parsed.token, session.token))) {
      await this.rememberDead(sessionIdToken)
      return null
    }
    if (session.expiresAt && session.expiresAt.getTime() < this.now()) {
      await this.rememberDead(sessionIdToken)
      return null
    }
    const result = { ...session, token: parsed.token }
    if (
      session.expiresAt && session.expiresAt.getTime() < this.now() + this.sessionDurationMs / 4
    ) {
      const updated = await this.store.updateSession(session.id, {
        expiresAt: this.getSessionExpirationDate(),
      })
      if (updated) {
        return { ...updated, token: parsed.token }
      }
    }
    return result
  }

  /** Revoke the session named by a cookie value. */
  async delete(sessionIdToken: string): Promise<boolean> {
    const parsed = this.parseSessionIdToken(sessionIdToken)
    if (!parsed) {
      return false
    }
    const session = await this.store.getSession(parsed.id)
    if (!session || !(await this.crypto.verify(parsed.token, session.token))) {
      return false
    }
    await this.store.deleteSession(parsed.id)
    await this.rememberDead(sessionIdToken)
    return true
  }

  async deleteAll(userId: number): Promise<void> {
    await this.store.deleteAllSessions(userId)
  }

  async deleteExpired(): Promise<void> {
    await this.store.deleteExpiredSessions()
  }

  get(id: number): Promise<null | Session> {
    return this.store.getSession(id)
  }

  getAll(userId: number): Promise<Session[]> {
    return this.store.getAllSessions(userId)
  }

  update(id: number, session: Partial<SessionBase>): Promise<null | Session> {
    return this.store.updateSession(id, session)
  }

  /** The opaque value a transport stores in its cookie. */
  getIdTokenForCookie(session: Session): string {
    return `${session.id}:${session.token}`
  }

  /**
   * Split a cookie value. A non-numeric or zero id is rejected up front: the
   * source's `parseInt` accepted `"1abc"` and `"001"`, which made two distinct
   * cookie values name one row.
   */
  parseSessionIdToken(sessionIdToken: string): null | { id: number; token: string } {
    const separator = sessionIdToken.indexOf(":")
    if (separator <= 0) {
      return null
    }
    const idPart = sessionIdToken.slice(0, separator)
    const token = sessionIdToken.slice(separator + 1)
    if (!SESSION_ID_PATTERN.test(idPart) || token.length === 0) {
      return null
    }
    return { id: Number(idPart), token }
  }

  private async rememberDead(sessionIdToken: string): Promise<void> {
    await this.negativeCache?.set(sessionIdToken, true, this.negativeCacheTtlMs)
  }

  private getSessionExpirationDate(): Date {
    return new Date(this.now() + this.sessionDurationMs)
  }
}
