/**
 * Writes a task back to CalDAV: a new task or subtask, an editor change applied as a lossless
 * patch of the original text, completing and reopening, and re-applying an edit to a fresh copy
 * after the server's version changed (a 412 on `If-Match`). The writing is {@link newTodo},
 * {@link patchTodo}, {@link completeTodo} and {@link reopenTodo}; this file adds the resource side
 * (`href`, `etag`, moving between lists, the undo text) on top. Nothing here reads the clock or
 * the network: the caller passes `now` and the new `UID`.
 *
 * @module
 */

import { type IcalComponent, parseIcal, serializeIcal } from "./ical.ts"
import {
  type Alarm,
  type AlarmInput,
  AlarmRelated,
  type AlarmTrigger,
  AlarmTriggerKind,
  completeTodo,
  CompleteTodoErrorCode,
  CompleteTodoKind,
  findMaster,
  newTodo,
  patchTodo,
  readTodo,
  reopenTodo,
  type TodoPatch,
} from "./ical-tasks.ts"
import { parseTask, type Task, type TaskDate } from "./ical-tasks-model.ts"
import { formatRrule, parseRrule } from "./rrule.ts"

/** The fields a new task can start with. */
export interface NewTaskFields {
  title: string
  notes?: string
  /** A date, a floating time or a UTC time: a new text has no `VTIMEZONE` for a zoned one. */
  due?: TaskDate
  start?: TaskDate
  /** The iCalendar `PRIORITY`, 0 to 9. */
  priority?: number
  tags?: string[]
}

export interface NewTaskContext {
  /** The new task's `UID`, generated by the caller. */
  uid: string
  now: Date
  /** The `PRODID` the new text carries: the app's own. */
  prodid: string
  /** The `href` of the list the task goes into. Ignored for a subtask: it joins its parent's. */
  listHref: string
  /** Makes the task a subtask of this one. */
  parent?: Task
}

export type CreateResult =
  | { success: true; output: CreateOutput; error: null }
  | { success: false; output: null; error: string }

export interface CreateOutput {
  uid: string
  /** The list the task goes into: the parent's for a subtask. */
  listHref: string
  /** Where to create the resource: the list plus `<uid>.ics`. */
  href: string
  ics: string
}

/** Builds the text for a new task. A subtask carries its parent's `UID` in `RELATED-TO`. */
export function createTask(fields: NewTaskFields, context: NewTaskContext): CreateResult {
  const patch: TodoPatch = { summary: fields.title }
  if (fields.notes) patch.description = fields.notes
  if (fields.due) patch.due = fields.due
  if (fields.start) patch.start = fields.start
  if (fields.priority) patch.priority = fields.priority
  if (fields.tags?.length) patch.categories = fields.tags
  if (context.parent) patch.relatedTo = [{ uid: context.parent.uid, type: `PARENT` }]
  const built = newTodo(patch, { uid: context.uid, now: context.now, prodid: context.prodid })
  if (!built.success) return { success: false, output: null, error: built.error.message }
  const listHref = context.parent?.listHref ?? context.listHref
  const href = `${listHref.endsWith(`/`) ? listHref : `${listHref}/`}${context.uid}.ics`
  return {
    success: true,
    output: { uid: context.uid, listHref, href, ics: serializeIcal(built.output) },
    error: null,
  }
}

/** The task fields the editor changes. */
export enum EditField {
  Title = 1,
  Notes,
  Due,
  Start,
  Priority,
  Tags,
  List,
  SortOrder,
  /** The repeat rule ({@link TaskEdit.repeatRule}). */
  Repeat,
  /** The reminders ({@link TaskEdit.reminders}). */
  Reminders,
}

/**
 * What the editor changed. A field left out stays as it is; `null` clears `due`, `start` and
 * `sortOrder`.
 */
export interface TaskEdit {
  title?: string
  notes?: string
  due?: TaskDate | null
  start?: TaskDate | null
  /** The iCalendar `PRIORITY`, 0 to 9. */
  priority?: number
  tags?: string[]
  /**
   * The `href` of another list. The task moves there: see {@link EditOutput.moveToList}. Its
   * subtasks stay in the old list (a v1 decision), so a parent's move does not move them.
   */
  listHref?: string
  sortOrder?: number | null
  /**
   * The `RRULE` value to write, such as `FREQ=WEEKLY;INTERVAL=1;BYDAY=MO` (build it with
   * `formatRrule`); `null` removes the repeat. It must be a rule `parseRrule` reads. A rule that
   * means the same as the one the task has (case, part order or a default part apart) counts as
   * unchanged, so a form that sends the rule back keeps the original line byte for byte.
   */
  repeatRule?: string | null
  /**
   * The reminders the task has afterwards; an empty list removes them all. Each is paired with
   * one existing `VALARM`, one to one and in order: same trigger, same `RELATED` and, when given,
   * the same action and description. A paired `VALARM` keeps its lines, vendor lines included;
   * an `action` or `description` that differs is a change and is written. Reminders read from a
   * task have no action, so one without `action` matches an existing reminder whatever its
   * action. A `VALARM` the editor cannot write (`EMAIL`, or no `TRIGGER`) is never touched, and
   * does not count as a reminder; a reminder without `action` or `description` and with the
   * trigger of such a `VALARM` stands for it, so a list read from the task does not duplicate it.
   */
  reminders?: AlarmInput[]
}

/** The result of {@link editTask}. */
export type EditResult =
  | { success: true; output: EditOutput; error: null }
  | { success: false; output: null; error: string }

export interface EditOutput {
  /** The task as it reads after the edit. `etag` is still the old one: the save returns a new one. */
  task: Task
  /** The patched text to send. */
  ics: string
  /**
   * Set when the edit moves the task to another list. The caller creates the resource at
   * `moveToHref` with `ics` and deletes the old one only after the new one exists, so a failed
   * move never loses the task. A CalDAV resource cannot change calendar in place.
   */
  moveToList?: string
  /** Where the moved resource goes: the target list plus the old file name. */
  moveToHref?: string
}

/**
 * Patches `task.ics` with `edit`. A refusal (a zoned date with no `VTIMEZONE`, a bad priority) is a
 * failure with a message and leaves the task as it was.
 */
export function editTask(task: Task, edit: TaskEdit, now: Date): EditResult {
  const parsed = parseIcal(task.ics)
  if (!parsed.success) return { success: false, output: null, error: parsed.error.message }
  const patch = toPatch(task, edit)
  const root = parsed.output
  if (typeof edit.repeatRule === `string` && patch.rrule !== undefined) {
    const rule = parseRrule(edit.repeatRule)
    if (!rule.success) return { success: false, output: null, error: rule.error.message }
    // Written in one spelling, so Tasks.org reads the same text whatever the caller typed.
    const written = formatRrule(rule.output)
    if (!written.success) return { success: false, output: null, error: written.error.message }
    patch.rrule = written.output
    const start = edit.start === undefined ? task.start : edit.start
    const due = edit.due === undefined ? task.due : edit.due
    if (!start && !due) {
      return {
        success: false,
        output: null,
        error: `A task needs a start or due date to repeat from`,
      }
    }
  }
  // A VALARM the editor cannot represent (EMAIL, no trigger) is set aside and put back as it was.
  const master = findMaster(root, `VTODO`)
  let setAside: IcalComponent[] = []
  if (edit.reminders !== undefined && master) {
    const alarms = alarmsOf(root)
    const paired = pairReminders(alarms, edit.reminders)
    if (!paired.unchanged) {
      const children = master.components.filter((child) => child.name.toUpperCase() === `VALARM`)
      setAside = children.filter((_, at) => !isEditable(alarms[at]!))
      master.components = master.components.filter((child) => !setAside.includes(child))
      const wanted = paired.entries.flatMap(({ entry, at, foreign }): AlarmInput[] => {
        if (foreign) return []
        if (at === undefined) return [entry]
        const found = alarms[at]!
        const action = found.action!.toUpperCase() as `DISPLAY` | `AUDIO`
        const adopted: AlarmInput = { ...entry, action }
        if (action === `DISPLAY` && found.description !== undefined) {
          adopted.description = found.description
        }
        return [adopted]
      })
      patch.alarms = wanted.length ? wanted : null
    }
  }
  const patched = patchTodo(root, patch, { now })
  if (!patched.success) return { success: false, output: null, error: patched.error.message }
  if (setAside.length) findMaster(root, `VTODO`)!.components.push(...setAside)
  const ics = serializeIcal(parsed.output)
  // The list is where the task lives, not a property of the text, so it is carried over as given.
  const listHref = edit.listHref ?? task.listHref
  const moved = listHref !== task.listHref
  const href = moved
    ? `${listHref.endsWith(`/`) ? listHref : `${listHref}/`}${task.href.split(`/`).pop()}`
    : task.href
  const read = parseTask({ href, etag: task.etag, listHref, ics })
  if (!read.success) return { success: false, output: null, error: read.error }
  const output: EditOutput = { task: read.output, ics }
  if (moved) {
    output.moveToList = listHref
    output.moveToHref = href
  }
  return { success: true, output, error: null }
}

function toPatch(task: Task, edit: TaskEdit): TodoPatch {
  const patch: TodoPatch = {}
  // Unchanged fields stay out of the patch, so lines another client wrote keep their bytes.
  if (edit.title !== undefined) patch.summary = edit.title
  // Empty notes remove the line; an empty `DESCRIPTION:` would be left otherwise.
  if (edit.notes !== undefined && edit.notes !== task.notes) {
    patch.description = edit.notes === `` ? null : edit.notes
  }
  if (edit.due !== undefined) patch.due = edit.due
  if (edit.start !== undefined) patch.start = edit.start
  // A task without PRIORITY reads as 0, so an unchanged 0 must not write `PRIORITY:0`.
  if (edit.priority !== undefined && edit.priority !== task.priority) patch.priority = edit.priority
  if (edit.tags !== undefined && !sameList(edit.tags, task.tags)) {
    patch.categories = edit.tags.length ? edit.tags : null
  }
  if (edit.sortOrder !== undefined) patch.sortOrder = edit.sortOrder
  if (edit.repeatRule !== undefined && !same(ruleOf(task.repeatRule), ruleOf(edit.repeatRule))) {
    patch.rrule = edit.repeatRule
  }
  return patch
}

/** The reminders of a task text, in order, as written (not only the ones the editor can write). */
function alarmsOf(root: IcalComponent): Alarm[] {
  return readTodo(root)?.alarms ?? []
}

function alarmsOfTask(task: Task): Alarm[] {
  const parsed = parseIcal(task.ics)
  return parsed.success ? alarmsOf(parsed.output) : []
}

/** A reminder the editor can write: DISPLAY or AUDIO, with a trigger. */
function isEditable(alarm: Alarm): boolean {
  const action = alarm.action?.toUpperCase()
  return alarm.trigger !== undefined && (action === `DISPLAY` || action === `AUDIO`)
}

type TriggerLike = AlarmTrigger | AlarmInput[`trigger`]

/** What makes two triggers the same reminder, whatever the text that wrote them. */
function triggerKey(trigger: TriggerLike): string {
  if (trigger.kind === AlarmTriggerKind.Absolute) {
    return `at ${trigger.at.date}T${trigger.at.time ?? `00:00:00`}`
  }
  return `${trigger.related ?? AlarmRelated.Start} ${trigger.duration.toUpperCase()}`
}

interface Pairing {
  entries: { entry: AlarmInput; at?: number; foreign?: boolean }[]
  /** Every sent reminder is one the text has and the text has no other reminder the editor can write. */
  unchanged: boolean
}

/**
 * Pairs the reminders the editor sent with the VALARMs the text has, one to one and in order. A
 * reminder matches a VALARM with its trigger (and `RELATED`) and, when it names them, its action
 * and description. One that names neither and matches only a VALARM the editor cannot write
 * (EMAIL) stands for that VALARM, which stays as it is.
 */
function pairReminders(alarms: Alarm[], list: AlarmInput[]): Pairing {
  const used = new Set<number>()
  const entries = list.map((entry): Pairing[`entries`][number] => {
    const key = triggerKey(entry.trigger)
    const at = alarms.findIndex((alarm, index) =>
      !used.has(index) && isEditable(alarm) && triggerKey(alarm.trigger!) === key &&
      (entry.action === undefined || entry.action === alarm.action!.toUpperCase()) &&
      (entry.description === undefined || entry.description === alarm.description)
    )
    if (at >= 0) {
      used.add(at)
      return { entry, at }
    }
    if (entry.action === undefined && entry.description === undefined) {
      const foreign = alarms.findIndex((alarm, index) =>
        !used.has(index) && !isEditable(alarm) && alarm.trigger !== undefined &&
        triggerKey(alarm.trigger) === key
      )
      if (foreign >= 0) {
        used.add(foreign)
        return { entry, at: foreign, foreign: true }
      }
    }
    return { entry }
  })
  const unchanged = entries.every((item) => item.at !== undefined) &&
    alarms.every((alarm, index) => !isEditable(alarm) || used.has(index))
  return { entries, unchanged }
}

/** The reminders a task has that the editor can write, with action and description. */
function reminderSignature(task: Task): string[] {
  return alarmsOfTask(task).filter(isEditable).map((alarm) =>
    `${alarm.action!.toUpperCase()} ${triggerKey(alarm.trigger!)} ${alarm.description ?? ``}`
  )
}

/** A rule in one spelling, or the text itself when `parseRrule` does not read it. */
function ruleOf(text: string | null | undefined): string | null {
  if (text === undefined || text === null) return null
  const parsed = parseRrule(text)
  const written = parsed.success ? formatRrule(parsed.output) : undefined
  return written?.success ? written.output : text
}

function sameList(a: string[], b: string[]): boolean {
  return a.length === b.length && a.every((item, i) => item === b[i])
}

export enum RebaseKind {
  /** The edit was applied to the fresh copy. */
  Applied = 1,
  /** Both sides changed the same field to different values. */
  Collision,
}

export type RebaseResult =
  | { success: true; output: { kind: RebaseKind.Applied } & EditOutput; error: null }
  | { success: true; output: { kind: RebaseKind.Collision; fields: EditField[] }; error: null }
  | { success: false; output: null; error: string }

/**
 * Re-applies `edit`, made on `base`, to `theirs`, the fresh copy from the server. A field counts as
 * touched by the edit when its value differs from `base`, and as touched by the server when
 * `theirs` differs from `base`; if both ended up at the same value there is no collision.
 *
 * Never apply the whole edit with {@link editTask} to the fresh copy: a form sends every field, and
 * the untouched ones would revert what the other side changed. Use this or {@link keepMine}.
 */
export function rebaseEdit(base: Task, edit: TaskEdit, theirs: Task, now: Date): RebaseResult {
  const fields = collisions(base, edit, theirs)
  if (fields.length) {
    return { success: true, output: { kind: RebaseKind.Collision, fields }, error: null }
  }
  const applied = keepMine(base, edit, theirs, now)
  if (!applied.success) return applied
  return { success: true, output: { kind: RebaseKind.Applied, ...applied.output }, error: null }
}

/**
 * "Keep mine": applies the fields `edit` really changed (against `base`) to `theirs`, overwriting
 * the server's value where both changed the same field and leaving every other server change alone.
 * Use it instead of {@link editTask} on `theirs`: a form sends every field, and the untouched ones
 * would revert what the other side changed.
 */
export function keepMine(base: Task, edit: TaskEdit, theirs: Task, now: Date): EditResult {
  return editTask(theirs, changesOf(base, edit), now)
}

/**
 * The part of `edit` that differs from `base`. A field the editor sent back as it was must not
 * overwrite what the server holds now.
 */
function changesOf(base: Task, edit: TaskEdit): TaskEdit {
  const changes: Record<string, unknown> = {}
  for (const { key, read, equals } of FIELDS) {
    if (edit[key] === undefined) continue
    if (!(equals ? equals(base, edit) : same(read(base), edit[key]))) changes[key] = edit[key]
  }
  return changes as TaskEdit
}

/** The fields both sides changed, to different values. */
export function collisions(base: Task, edit: TaskEdit, theirs: Task): EditField[] {
  const out: EditField[] = []
  for (const { field, key, read, equals } of FIELDS) {
    if (edit[key] === undefined) continue
    const is = (task: Task) => equals ? equals(task, edit) : same(read(task), edit[key])
    if (!is(base) && !same(read(base), read(theirs)) && !is(theirs)) out.push(field)
  }
  return out
}

const FIELDS: {
  field: EditField
  key: keyof TaskEdit
  read: (task: Task) => unknown
  /** Whether the edit's value for this field is what `task` has. Default: `read` against the edit. */
  equals?: (task: Task, edit: TaskEdit) => boolean
}[] = [
  { field: EditField.Title, key: `title`, read: (t) => t.title },
  { field: EditField.Notes, key: `notes`, read: (t) => t.notes },
  { field: EditField.Due, key: `due`, read: (t) => t.due },
  { field: EditField.Start, key: `start`, read: (t) => t.start },
  { field: EditField.Priority, key: `priority`, read: (t) => t.priority },
  { field: EditField.Tags, key: `tags`, read: (t) => t.tags },
  { field: EditField.List, key: `listHref`, read: (t) => t.listHref },
  { field: EditField.SortOrder, key: `sortOrder`, read: (t) => t.sortOrder },
  {
    field: EditField.Repeat,
    key: `repeatRule`,
    read: (t) => ruleOf(t.repeatRule),
    equals: (t, e) => same(ruleOf(t.repeatRule), ruleOf(e.repeatRule)),
  },
  {
    field: EditField.Reminders,
    key: `reminders`,
    read: reminderSignature,
    equals: (t, e) => pairReminders(alarmsOfTask(t), e.reminders ?? []).unchanged,
  },
]

function same(a: unknown, b: unknown): boolean {
  if (Array.isArray(a) && Array.isArray(b)) {
    return a.length === b.length && a.every((item, at) => same(item, b[at]))
  }
  if (isDate(a) && isDate(b)) {
    return a.kind === b.kind && a.date === b.date && a.time === b.time && a.tzid === b.tzid
  }
  return (a ?? null) === (b ?? null)
}

function isDate(value: unknown): value is TaskDate {
  return typeof value === `object` && value !== null && `kind` in value
}

/** What a successful change did to the task. */
export enum CompleteKind {
  /** A repeating task moved to its next occurrence and is still open. */
  Advanced = 1,
  /** The task is completed. */
  Completed,
  /** A completed task is open again. */
  Reopened,
}

export interface CompleteError {
  code: CompleteTodoErrorCode
  /** The library's message, for a log or a fallback; an app words its own text from `code`. */
  message: string
}

export type CompleteResult =
  | { success: true; output: CompleteOutput; error: null }
  | { success: false; output: null; error: CompleteError }

export interface CompleteOutput {
  /** Whether the task advanced to its next occurrence or is completed. */
  kind: CompleteKind
  /** The task as it reads after the change. */
  task: Task
  /** The text to send. */
  ics: string
  /** The text from before, byte for byte. Writing it back undoes the change. */
  undoIcs: string
}

/**
 * The codes that mean the repeat rule or the dates are outside what can be reproduced, as opposed
 * to a broken text. An app shows its own "complete this in the other app" wording for these.
 */
export const COMPLETE_REFUSED_BY_RULE: ReadonlySet<CompleteTodoErrorCode> = new Set([
  CompleteTodoErrorCode.UnsupportedRule,
  CompleteTodoErrorCode.NoDueDate,
  CompleteTodoErrorCode.UnusableDate,
])

/** Completes `task`; a repeating task moves to its next occurrence instead. */
export function completeTask(task: Task, now: Date): CompleteResult {
  return change(task, (root) => {
    const result = completeTodo(root, { now })
    return result.success
      ? {
        success: true,
        kind: result.output.kind === CompleteTodoKind.Advanced
          ? CompleteKind.Advanced
          : CompleteKind.Completed,
      }
      : { success: false, error: result.error }
  })
}

/**
 * Reopens a completed task. It undoes the completion of a task that ended its series; to undo the
 * move of a repeating task, write back the `undoIcs` of that completion.
 */
export function reopenTask(task: Task, now: Date): CompleteResult {
  return change(task, (root) => {
    const result = reopenTodo(root, { now })
    return result.success
      ? { success: true, kind: CompleteKind.Reopened }
      : { success: false, error: result.error }
  })
}

type Step =
  | { success: true; kind: CompleteKind }
  | { success: false; error: { code: CompleteTodoErrorCode; message: string } }

function change(task: Task, run: (root: IcalComponent) => Step): CompleteResult {
  const parsed = parseIcal(task.ics)
  if (!parsed.success) return fail(CompleteTodoErrorCode.NoTodo, parsed.error.message)
  const step = run(parsed.output)
  if (!step.success) {
    const { code, message } = step.error
    return fail(code, message)
  }
  const ics = serializeIcal(parsed.output)
  const read = parseTask({ href: task.href, etag: task.etag, listHref: task.listHref, ics })
  if (!read.success) return fail(CompleteTodoErrorCode.NoTodo, read.error)
  return {
    success: true,
    output: { kind: step.kind, task: read.output, ics, undoIcs: task.ics },
    error: null,
  }
}

function fail(code: CompleteTodoErrorCode, message: string): CompleteResult {
  return { success: false, output: null, error: { code, message } }
}
