/**
 * Worktree-aware git hook installer.
 *
 * `rostok/scripts/hooks/install.ts` is the source: it resolves the *common* git
 * directory with `git rev-parse --git-common-dir` so the hooks are shared by
 * every worktree of a repository instead of being installed into one worktree's
 * private `$GIT_DIR`. Four things were wrong with it, all fixed here:
 *
 * 1. `Deno.env.get("GIT_DIR")` ran at **module scope** (line 10), so importing
 *    the file read the process environment; it is an injected {@link EnvReader}
 *    now.
 * 2. The path from `git rev-parse` was used as-is. In the main worktree git
 *    prints a *relative* `.git`, so `hooks` landed relative to whatever the
 *    process cwd happened to be. Relative results are resolved against the cwd
 *    git was run in.
 * 3. A failing `git rev-parse` fell back to `<cwd>/.git`, creating a directory
 *    named `.git` that turns its parent into something git then treats as a
 *    repository. It throws instead, unless the caller names a fallback.
 * 4. Content that already matched skipped the `chmod`, so a hook that had lost
 *    its execute bit stayed silently dead — git ignores a non-executable hook.
 *    A matching file with the wrong mode is repaired.
 *
 * Plus one security fix that the source could not have had: the hook path is
 * `lstat`ed and a symlink is refused. `writeTextFile` follows a symlink, so a
 * link at `.git/hooks/pre-commit` would redirect the write outside the
 * repository — the same class of bug the age64 env writer avoids by refusing
 * symlinks.
 */

import type { EnvReader } from "../env.ts"
import type { FileSystem } from "../fs.ts"
import { isNotFound } from "../fs.ts"
import type { Logger } from "../console.ts"
import type { CommandRunner } from "../run-command.ts"
import { runCommand } from "../run-command.ts"

/** One hook to install. */
export interface HookDefinition {
  /** File name under `hooks/`, e.g. `pre-commit`. */
  name: string
  /** Full script content, shebang included. */
  content: string
}

/** What happened to one hook. */
export type HookStatus =
  /** The file did not exist and was written. */
  | "installed"
  /** The file existed with different content and was overwritten. */
  | "updated"
  /** The file existed with the same content and the right mode — nothing written. */
  | "unchanged"
  /** The content matched but the execute bit was missing; the mode was repaired. */
  | "repaired"

/** Outcome for one hook. */
export interface HookResult {
  /** Hook name. */
  name: string
  /** Path the installer acted on. */
  path: string
  /** What it did. */
  status: HookStatus
}

/** Result of a whole run. */
export interface InstallHooksResult {
  /** Common hooks directory, absolute once the caller passed an absolute cwd. */
  hooksDir: string
  /** One entry per hook, in {@link HookDefinition} order. */
  results: HookResult[]
}

/** Raised for a configuration or filesystem problem the installer refuses to paper over. */
export class HookInstallError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "HookInstallError"
  }
}

/**
 * The hooks `rostok` installs, kept as the default.
 *
 * `pre-commit` checks and re-encrypts; `post-checkout` and `post-merge` decrypt
 * so a worktree is usable as soon as it exists. Override the whole list through
 * {@link InstallHooksOptions.hooks} — a caller with no `.env.age` does not want a
 * hook that fails on every checkout.
 */
export const DEFAULT_HOOKS: readonly HookDefinition[] = [
  {
    name: "pre-commit",
    content: `#!/bin/sh
# Generated by @ts-libs/ops — edit the installer, not this file.
set -eu
deno task check && deno task env:encrypt
`,
  },
  {
    name: "post-checkout",
    content: `#!/bin/sh
# Generated by @ts-libs/ops — edit the installer, not this file.
set -eu
deno task env:decrypt
`,
  },
  {
    name: "post-merge",
    content: `#!/bin/sh
# Generated by @ts-libs/ops — edit the installer, not this file.
set -eu
deno task env:decrypt
`,
  },
]

/** Everything {@link installHooks} and {@link resolveGitCommonDir} need. */
export interface InstallHooksOptions {
  /** Filesystem port. */
  fs: FileSystem
  /** Command runner port, used for `git rev-parse`. */
  runner: CommandRunner
  /**
   * Environment reader, consulted only for `GIT_DIR`. Defaults to "no override":
   * reading the process environment is the caller's decision, never a side
   * effect of importing this module.
   */
  env?: EnvReader
  /** Directory git is run in, and the base for a relative result. Defaults to `.`. */
  cwd?: string
  /**
   * Directory to fall back to when `git rev-parse` fails. Absent by default:
   * creating `<cwd>/.git` turns an arbitrary directory into something git treats
   * as a repository, which is worse than failing.
   */
  fallbackDir?: string
  /** Hooks to install. Defaults to {@link DEFAULT_HOOKS}. */
  hooks?: readonly HookDefinition[]
  /**
   * Set the execute bit. Defaults to `true` everywhere except Windows, where a
   * hook needs no mode bits. A hook without it is silently ignored by git.
   */
  executable?: boolean
  /** Mode written when `executable`. Defaults to `0o755`. */
  mode?: number
  /** Allow overwriting a hook path that is a symlink. Defaults to `false`. */
  allowSymlink?: boolean
  /** Logger. Defaults to silence — the caller owns the output. */
  logger?: Logger
}

/**
 * Resolve the repository's *common* git directory.
 *
 * @throws {HookInstallError} When `git rev-parse --git-common-dir` fails and no
 * `fallbackDir` was given, or when git prints nothing.
 */
export async function resolveGitCommonDir(options: InstallHooksOptions): Promise<string> {
  // A blank override is an *unset* override: an `EnvReader` that does not
  // normalise `""` to `undefined` (a plain `{ get: () => "" }`, a shell that
  // exports an empty variable) would otherwise produce "/hooks" and install the
  // hooks at the filesystem root. A relative override is resolved against the cwd
  // like the value git itself prints.
  const override = options.env?.get("GIT_DIR")?.trim()
  if (override !== undefined && override !== "") {
    return resolveAgainstCwd(override, options.cwd)
  }

  const result = await runCommand(options.runner, ["git", "rev-parse", "--git-common-dir"], {
    cwd: options.cwd,
  })

  if (!result.success) {
    if (options.fallbackDir !== undefined) return options.fallbackDir
    throw new HookInstallError(
      `git rev-parse --git-common-dir failed${
        options.cwd === undefined ? "" : ` in ${options.cwd}`
      }: ${result.error.trim() || "no stderr"}`,
    )
  }

  const reported = result.output.trim()
  if (reported === "") {
    throw new HookInstallError("git rev-parse --git-common-dir printed nothing")
  }
  return resolveAgainstCwd(reported, options.cwd)
}

/**
 * Join a possibly-relative directory to the cwd and resolve its segments.
 *
 * Both sources of the common directory use this: the value git prints, and the
 * `GIT_DIR` override — a caller that sets `GIT_DIR=.git` means the same thing git
 * does, and returning a bare `.git` would put the hooks in whatever directory the
 * *process* happens to have as its cwd.
 */
function resolveAgainstCwd(value: string, cwd: string | undefined): string {
  if (value.startsWith("/")) return resolveSegments(value)
  const base = resolveSegments((cwd ?? ".").replace(/\/+$/, ""))
  return resolveSegments(`${base === "" ? "." : base}/${value.replace(/^\.\//, "")}`)
}

const HOOK_NAME = /^[a-z][a-z0-9-]*$/

/**
 * Resolve `.` and `..` lexically.
 *
 * git prints the common directory *relative to the cwd* in the main worktree
 * (`rev-parse --git-common-dir` → `.git`) and absolute in a linked worktree
 * (→ `/home/dev/app/.git`), so the relative form has to be joined to the cwd git
 * ran in. Joining without resolving leaves `…/worktrees/feature/../../.git`,
 * which works but reads as a mistake in a log line and compares unequal to the
 * path a caller would compute.
 */
function resolveSegments(path: string): string {
  const absolute = path.startsWith("/")
  const segments: string[] = []
  for (const segment of path.split("/")) {
    if (segment === "" || segment === ".") continue
    if (segment === "..") {
      if (segments.length > 0 && segments[segments.length - 1] !== "..") {
        segments.pop()
        continue
      }
      if (absolute) continue
    }
    segments.push(segment)
  }
  const joined = segments.join("/")
  if (absolute) return `/${joined}`
  return joined === "" ? "." : joined
}

function isUnchanged(existing: string, content: string): boolean {
  return existing.replace(/\s+$/, "") === content.replace(/\s+$/, "")
}

/**
 * Install the hooks into the common git directory.
 *
 * Idempotent: a hook whose content already matches is not rewritten, and its
 * mode is only touched when the execute bit is missing.
 *
 * @throws {HookInstallError} When a hook path is a symlink and `allowSymlink` is
 * not set, or when the hooks directory cannot be created.
 */
export async function installHooks(options: InstallHooksOptions): Promise<InstallHooksResult> {
  const hooks = options.hooks ?? DEFAULT_HOOKS
  const executable = options.executable ?? Deno.build.os !== "windows"
  const mode = options.mode ?? 0o755
  const commonDir = await resolveGitCommonDir(options)
  const hooksDir = `${commonDir.replace(/\/+$/, "")}/hooks`

  options.logger?.info(`installing hooks in ${hooksDir}`)

  try {
    await options.fs.mkdir(hooksDir, { recursive: true })
  } catch (error) {
    if (isNotFound(error)) {
      throw new HookInstallError(`cannot create hooks directory ${hooksDir}: ${String(error)}`)
    }
  }

  const results: HookResult[] = []

  for (const hook of hooks) {
    if (!HOOK_NAME.test(hook.name)) {
      throw new HookInstallError(
        `"${hook.name}" is not a git hook name; expected lowercase letters, digits and dashes`,
      )
    }
    const path = `${hooksDir}/${hook.name}`

    let existing: string | null = null
    try {
      const stat = await options.fs.lstat(path)
      if (stat.isSymlink && options.allowSymlink !== true) {
        throw new HookInstallError(
          `refusing to write through the symlink at ${path}; remove it or pass allowSymlink`,
        )
      }
      existing = await options.fs.readTextFile(path)
    } catch (error) {
      if (error instanceof HookInstallError) throw error
      if (!isNotFound(error)) throw error
    }

    if (existing !== null && isUnchanged(existing, hook.content)) {
      const stat = await options.fs.stat(path)
      const needsMode = executable && stat.mode !== null && (stat.mode & 0o111) === 0
      if (!needsMode) {
        results.push({ name: hook.name, path, status: "unchanged" })
        continue
      }
      await options.fs.chmod(path, mode)
      options.logger?.info(`${hook.name}: mode repaired to ${mode.toString(8)}`)
      results.push({ name: hook.name, path, status: "repaired" })
      continue
    }

    await options.fs.writeTextFile(path, hook.content)
    if (executable) await options.fs.chmod(path, mode)

    const status: HookStatus = existing === null ? "installed" : "updated"
    options.logger?.info(`${hook.name}: ${status}`)
    results.push({ name: hook.name, path, status })
  }

  return { hooksDir, results }
}
